# Generated by Django 5.2.8 on 2025-12-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighthistory',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
    ]
