# Generated by Django 5.2.8 on 2025-12-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_flighthistory_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedflight',
            name='aircraft_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trackedflight',
            name='baggage_claim',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackedflight',
            name='gate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackedflight',
            name='inbound_flight_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackedflight',
            name='inbound_origin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackedflight',
            name='terminal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
