# Generated by Django 5.2.8 on 2025-12-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trackedflight_aircraft_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedflight',
            name='arrivalTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
