# Generated by Django 5.2.8 on 2025-12-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trackedflight_arrivaltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedflight',
            name='airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
